server:
  port: ${PORT} 
  address: 0.0.0.0

plugins:
  - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.4"
    repository: "https://maven.lavalink.dev/releases"
  - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.2.0"
    repository: "https://maven.lavalink.dev/releases"

lavalink:
  server:
    password: "chrxmaticc2026"
    sources:
      youtube: true
      soundcloud: true
      http: true
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

logging:
  level:
    root: INFO
    lavalink: INFO
